### ISSUE TITLE
remix errors

### ISSUE THREAD

**Issue by erwan-joly** [mat-sz/lettersanitizer#5]
Hi I'm having a bug when trying to use this package as part of react-letter when trying to use with remix. Any idea on how I could fix this ?

Here a repro: https://github.com/erwan-joly/reprobugletterremix

The error I'm getting:
```
C:\dev\reprobugletterremix\node_modules\lettersanitizer\lib\index.js:1
import { allowedTags, allowedCssProperties, removeWithContents, } from './constants';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1094:15)
    at Module._compile (node:internal/modules/cjs/loader:1129:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\dev\reprobugletterremix\node_modules\react-letter\dist\react-letter.cjs.development.js:8:23)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\dev\reprobugletterremix\node_modules\react-letter\dist\index.js:7:20)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\dev\reprobugletterremix\app\root.tsx:5:24)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at C:\dev\reprobugletterremix\node_modules\@remix-run\serve\dist\index.js:43:17
    at Layer.handle [as handle_request] (C:\dev\reprobugletterremix\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\dev\reprobugletterremix\node_modules\express\lib\router\route.js:144:13)
    at next (C:\dev\reprobugletterremix\node_modules\express\lib\router\route.js:140:7)
    at next (C:\dev\reprobugletterremix\node_modules\express\lib\router\route.js:140:7)
    at next (C:\dev\reprobugletterremix\node_modules\express\lib\router\route.js:140:7)
    at next (C:\dev\reprobugletterremix\node_modules\express\lib\router\route.js:140:7)
    at next (C:\dev\reprobugletterremix\node_modules\express\lib\router\route.js:140:7)
    at next (C:\dev\reprobugletterremix\node_modules\express\lib\router\route.js:140:7)
    at Route.dispatch (C:\dev\reprobugletterremix\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\dev\reprobugletterremix\node_modules\express\lib\router\layer.js:95:5)
    at C:\dev\reprobugletterremix\node_modules\express\lib\router\index.js:284:15
    at param (C:\dev\reprobugletterremix\node_modules\express\lib\router\index.js:365:14)
    at param (C:\dev\reprobugletterremix\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\dev\reprobugletterremix\node_modules\express\lib\router\index.js:421:3)
    at next (C:\dev\reprobugletterremix\node_modules\express\lib\router\index.js:280:10)
    at logger (C:\dev\reprobugletterremix\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\dev\reprobugletterremix\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\dev\reprobugletterremix\node_modules\express\lib\router\index.js:328:13)
    at C:\dev\reprobugletterremix\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\dev\reprobugletterremix\node_modules\express\lib\router\index.js:346:12
```

**Comment by erwan-joly** [comment]
For people wondering:

run `npm install jsdom jsdom-global --save-dev`

in remix.config.js
```
serverDependenciesToBundle: ["react-letter","lettersanitizer"],
```
in entry.server.ts
```
require('jsdom-global')()
global.DOMParser = window.DOMParser
```
